"use client";

import "./globals.css";
import { Inter } from "next/font/google";
import NavLink from "@/components/NavLink";
import { Discord } from "@/components/icons";
import { useParams } from "next/navigation";
import { data } from "@/data";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const params = useParams();

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen text-gray-100">
          <div className="p-3 space-y-2 overflow-y-scroll bg-gray-900">
            <NavLink href="/">
              <Discord className="h-5 w-7" />
            </NavLink>

            <hr className="border-t-white/[.06] border-t-2 rounded mx-2" />

            {data.map((server) => (
              <NavLink
                href={`/servers/${server.id}/channels/${server.categories[0].channels[0].id}`}
                active={Number(server.id) === Number(params.sid)}
                key={server.id}
              >
                <img src={`/servers/${server.img}`} alt="" />
              </NavLink>
            ))}
          </div>

          {children}
        </div>
      </body>
    </html>
  );
}
